### ISSUE TITLE
Godaddy renew fails: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/mydomain.eu/records

### ISSUE THREAD

**Issue by forouher** [adferrand/dnsrobocert#172]
Tested with docker image adferrand/dnsrobocert:3.7.0

Logs:

```
dnsrobocert_1                | ----------
dnsrobocert_1                | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
dnsrobocert_1                | Plugins selected: Authenticator manual, Installer None
dnsrobocert_1                | Cert is due for renewal, auto-renewing...
dnsrobocert_1                | Renewing an existing certificate
dnsrobocert_1                | Performing the following challenges:
dnsrobocert_1                | dns-01 challenge for sub.mydomain.eu
dnsrobocert_1                | dns-01 challenge for sub.mydomain.eu
dnsrobocert_1                | Running manual-auth-hook command: /usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp5zy2xtw8/dnsrobocert-runtime.yml" -l "sub.mydomain.eu"
dnsrobocert_1                | Output from manual-auth-hook command python3:
dnsrobocert_1                | Executing auth hook for domain sub.mydomain.eu, lineage sub.mydomain.eu.
dnsrobocert_1                | 
dnsrobocert_1                | manual-auth-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp5zy2xtw8/dnsrobocert-runtime.yml" -l "sub.mydomain.eu"" returned error code 1
dnsrobocert_1                | Error output from manual-auth-hook command python3:
dnsrobocert_1                | Error while executing the `auth` hook:
dnsrobocert_1                | 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/mydomain.eu/records
dnsrobocert_1                | Traceback (most recent call last):
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 42, in main
dnsrobocert_1                |     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 62, in auth
dnsrobocert_1                |     _txt_challenge(profile, token, domain, action="create")
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 200, in _txt_challenge
dnsrobocert_1                |     Client(lexicon_config).execute()
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/lexicon/client.py", line 88, in execute
dnsrobocert_1                |     return self.provider.create_record(record_type, name, content)
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 87, in create_record
dnsrobocert_1                |     return self._create_record(rtype, name, content)
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 119, in _create_record
dnsrobocert_1                |     self._put("/domains/{0}/records".format(domain), records)
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 165, in _put
dnsrobocert_1                |     return self._request("PUT", url, data=data, query_params=query_params)
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 317, in _request
dnsrobocert_1                |     result.raise_for_status()
dnsrobocert_1                |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
dnsrobocert_1                |     raise HTTPError(http_error_msg, response=self)
dnsrobocert_1                | requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/mydomain.eu/records
dnsrobocert_1                | 
dnsrobocert_1                | Running manual-auth-hook command: /usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp5zy2xtw8/dnsrobocert-runtime.yml" -l "sub.mydomain.eu"
dnsrobocert_1                | Output from manual-auth-hook command python3:
dnsrobocert_1                | Executing auth hook for domain sub.mydomain.eu, lineage sub.mydomain.eu.
dnsrobocert_1                | 
dnsrobocert_1                | manual-auth-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp5zy2xtw8/dnsrobocert-runtime.yml" -l "sub.mydomain.eu"" returned error code 1

```

Config:

```
draft: false
acme:
  email_account: xxxx
  staging: false
profiles:
- name: godaddy
  provider: godaddy
  provider_options:
    auth_key: XXX
    auth_secret:  XXX
certificates:
- name: sub.mydomain.eu
  domains:
  - sub.mydomain.eu
  - "*.sub.mydomain.eu"
  profile: godaddy

```

**Comment by forouher** [comment]
Tested it today with 3.8.3, now it works.

Closing this MR, thanks!
