### ISSUE TITLE
403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/

### ISSUE THREAD

**Issue by Ukropp** [adferrand/dnsrobocert#412]
When I run dnsrobocert, an authorisation error. It cannot create a TXT record.
**Log:**
```
2021-06-22 13:13:39  dnsrobocert.core.main[1] INFO Starting DNSroboCert.
2021-06-22 13:13:39  dnsrobocert.core.main[1] INFO Registering ACME account if needed.
2021-06-22 13:13:39  dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot register -n --user-agent-comment DNSroboCert/3.9.1 --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs -m example@gmail.com --agree-tos --server https://acme-staging-v02.api.letsencrypt.org/directory
----------
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
There is an existing account; registration of a duplicate account with this command is currently unsupported.
----------
2021-06-22 13:13:47 dnsrobocert.core.main[1] INFO Creating missing certificates if needed (~1min for each)
2021-06-22 13:13:47 dnsrobocert.core.main[1] INFO Handling the certificate for domain(s): example.com
----------
2021-06-22 13:13:47 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot certonly -n --user-agent-comment DNSroboCert/3.9.1 --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs --manual --preferred-challenges=dns --manual-auth-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c \"/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml\" -l \"example.com\"" --manual-cleanup-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c \"/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml\" -l \"example.com\"" --expand --deploy-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c \"/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml\" -l \"example.com\"" --server https://acme-staging-v02.api.letsencrypt.org/directory --cert-name example.com -d example.com
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Requesting a certificate for example.com
Performing the following challenges:
dns-01 challenge for example.com
Running manual-auth-hook command: /usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml" -l "example.com"
Output from manual-auth-hook command python:
Executing auth hook for domain example.com, lineage example.com.

manual-auth-hook command "/usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml" -l "example.com"" returned error code 1
Error output from manual-auth-hook command python:
Error while executing the `auth` hook:
403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/zones/example/dns_records
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 40, in main
    globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 61, in auth
    txt_challenge(certificate, profile, token, domain, action="create")
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/challenge.py", line 57, in txt_challenge
    Client(lexicon_config).execute()
  File "/usr/local/lib/python3.9/site-packages/lexicon/client.py", line 79, in execute
    return self.provider.create_record(record_type, name, content)
  File "/usr/local/lib/python3.9/site-packages/lexicon/providers/base.py", line 87, in create_record
    return self._create_record(rtype, name, content)
  File "/usr/local/lib/python3.9/site-packages/lexicon/providers/cloudflare.py", line 82, in _create_record
    payload = self._post(f"/zones/{self.domain_id}/dns_records", data)
  File "/usr/local/lib/python3.9/site-packages/lexicon/providers/base.py", line 162, in _post
    return self._request("POST", url, data=data, query_params=query_params)
  File "/usr/local/lib/python3.9/site-packages/lexicon/providers/cloudflare.py", line 206, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/zones/qwe/dns_records

Waiting for verification...
Challenge failed for domain example.com
dns-01 challenge for example.com
Cleaning up challenges
Running manual-cleanup-hook command: /usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml" -l "example.com"
Output from manual-cleanup-hook command python:
Executing cleanup hook for domain example.com, lineage example.com.

Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: example.com
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.example.com - check that a DNS record
   exists for this domain
----------
2021-06-22 13:14:01 924dc1c75c80 dnsrobocert.core.main[1] ERROR An error occurred while processing certificate config `{'domains': ['example.com'], 'profile': 'cloudflare'}`:
Command '['/usr/local/bin/python', '-m', 'dnsrobocert.core.certbot', 'certonly', '-n', '--user-agent-comment', 'DNSroboCert/3.9.1', '--config-dir', '/etc/letsencrypt', '--work-dir', '/etc/letsencrypt/workdir', '--logs-dir', '/etc/letsencrypt/logs', '--manual', '--preferred-challenges=dns', '--manual-auth-hook', '/usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml" -l "example.com"', '--manual-cleanup-hook', '/usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml" -l "example.com"', '--expand', '--deploy-hook', '/usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c "/tmp/tmp6ff6lwwb/dnsrobocert-runtime.yml" -l "example.com"', '--server', 'https://acme-staging-v02.api.letsencrypt.org/directory', '--cert-name', 'example.com', '-d', 'example.com']' returned non-zero exit status 1.
2021-06-22 13:14:01 924dc1c75c80 dnsrobocert.core.main[1] INFO Revoke and delete certificates if needed
```
**docker-compose:**
```
#certbot
  dnscertbot:
    image: adferrand/dnsrobocert:latest
    container_name: dnscertbot
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./certs:/etc/letsencrypt
      - ./dnsrobocert:/etc/dnsrobocert
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
**Config.yml**
```
#draft: true
acme:
  email_account: ${CLOUDFLARE_USERNAME}
  staging: true
profiles:
- name: cloudflare
  provider: cloudflare
  provider_options:
    auth_token: ${CLOUDFLARE_AUTH_TOKEN}
certificates:
- domains:
  - example.com
  profile: cloudflare
```

**API token permissions:**
![изображение](https://user-images.githubusercontent.com/55854392/122934986-a6a06d80-d378-11eb-8a79-f36468f026e6.png)

**Curl token test from server:**
```
ubuntu@docker:~/v2ray$ curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
>      -H "Authorization: Bearer ot81oC4rRaEUSMc2oTKrqweqwe" \
>      -H "Content-Type:application/json"
{"result":{"id":"3a6dd3a","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}
```

**DNS records:**

![изображение](https://user-images.githubusercontent.com/55854392/122936629-fa5f8680-d379-11eb-90bc-ab83d7edf4e0.png)

**Comment by oktayaa** [comment]
I have the same issue. I have also confirmed that if I call the url with the same information using curl it returns correctly. (I have only test /GET).

I have done a quick search and found similar issues in a few similar projects but all seem to have been fixed on the software. i.e user can't work around it.

I have also double checked that I do NOT have an acme_challenge TXT record for this zone.

**Comment by oktayaa** [comment]
Actually mine is a tiny bit different. I get "Client Error: Bad request"

letsencrypt.log.2:308: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones/<zoneid>

**Comment by adferrand** [comment]
I have also a cloudflare account, so I will verify that during the week end.

**Comment by adferrand** [comment]
Indeed, it is most likely the usage of a global API without `auth_username` set. I made that quite explicit in the inline help of `lexicon` itself, but not reporting it in the user documentation, neither for lexicon or dnsrobocert. I fix that.
