### ISSUE TITLE
docker executable is missing in docker image

### ISSUE THREAD

**Issue by dok529** [adferrand/dnsrobocert#483]
Version 3.11 of docker image: (/var/run/docker.sock is mounted)
```
Hook 'deploy-hook' ran with error output:
 2021-08-17 11:43:09 fba80af49106 dnsrobocert.core.utils[11] INFO Launching command: docker restart nginx
 Error while executing the `deploy` hook:
 [Errno 2] No such file or directory: 'docker'
 Traceback (most recent call last):
   File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 40, in main
     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
   File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 135, in deploy
     _autorestart(certificate)
   File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 180, in _autorestart
     utils.execute(["docker", "restart", container])
   File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/utils.py", line 52, in execute
     call(command, shell=shell, env=env)
   File "/usr/local/lib/python3.9/subprocess.py", line 368, in check_call
     retcode = call(*popenargs, **kwargs)
   File "/usr/local/lib/python3.9/subprocess.py", line 349, in call
     with Popen(*popenargs, **kwargs) as p:
   File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
     self._execute_child(args, executable, preexec_fn, close_fds,
   File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
     raise child_exception_type(errno_num, err_msg, err_filename)
 FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

In version 3.10.2 docker container `autorestart` is working correctly

**Comment by adferrand** [comment]
I will deploy a fix in few hours. Thanks for the report !
