### ISSUE TITLE
.com.de domain with namecheap not working

### ISSUE THREAD

**Issue by t-abraham** [adferrand/dnsrobocert#65]
if i use and domain which has name.tld.tld2 the authentication fails with namecheap.
if i use my other domain like name.tld it workd perfectly. both the domains are in the same namecheap account.

anyone know why and how to solve it?

```
letsencrypt-dns | 2019-10-17 15:13:07 [19] | manual-auth-hook command "/var/lib/letsencrypt/hooks/authenticator.sh" returned error code 1
letsencrypt-dns | 2019-10-17 15:13:07 [19] | Error output from manual-auth-hook command authenticator.sh:
letsencrypt-dns | 2019-10-17 15:13:07 [19] | Traceback (most recent call last):
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/namecheap.py", line 121, in _authenticate
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     xml = self.client._call('namecheap.domains.getInfo', extra_payload)  # pylint: disable=protected-access
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 144, in _call
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     xml = self._fetch_xml(payload, extra_payload)
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 137, in _fetch_xml
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     raise ApiError(error.attrib['Number'], error.text)
letsencrypt-dns | 2019-10-17 15:13:07 [19] | namecheap.ApiError: 2030166 - Domain is invalid
letsencrypt-dns | 2019-10-17 15:13:07 [19] | During handling of the above exception, another exception occurred:
letsencrypt-dns | 2019-10-17 15:13:07 [19] | Traceback (most recent call last):
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File "/usr/local/bin/lexicon", line 10, in <module>
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     sys.exit(main())
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     results = client.execute()
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File
letsencrypt-dns | 2019-10-17 15:13:07 [19] | "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 71, in execute
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     self.provider.authenticate()
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 69, in authenticate
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     return self._authenticate()
letsencrypt-dns | 2019-10-17 15:13:07 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/namecheap.py", line 127, in _authenticate
letsencrypt-dns | 2019-10-17 15:13:07 [19] |     raise Exception('Authentication failed: `%s`' % str(err))
letsencrypt-dns | 2019-10-17 15:13:07 [19] | Exception: Authentication failed: `2030166 - Domain is invalid`
letsencrypt-dns | 2019-10-17 15:13:07 [19] | Waiting for verification...
letsencrypt-dns | 2019-10-17 15:13:09 [19] | Challenge failed for domain mikrotik.com.de
letsencrypt-dns | 2019-10-17 15:13:09 [19] | dns-01 challenge for mikrotik.com.de
letsencrypt-dns | 2019-10-17 15:13:09 [19] | Cleaning up challenges
letsencrypt-dns | 2019-10-17 15:13:09 [19] | Running manual-cleanup-hook command: /var/lib/letsencrypt/hooks/cleanup.sh
letsencrypt-dns | 2019-10-17 15:13:10 [19] | manual-cleanup-hook command "/var/lib/letsencrypt/hooks/cleanup.sh" returned error code 1
letsencrypt-dns | 2019-10-17 15:13:10 [19] | Error output from manual-cleanup-hook command cleanup.sh:
letsencrypt-dns | 2019-10-17 15:13:10 [19] | Traceback (most recent call last):
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/namecheap.py", line 121, in _authenticate
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     xml = self.client._call('namecheap.domains.getInfo', extra_payload)  # pylint: disable=protected-access
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 144, in _call
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     xml = self._fetch_xml(payload, extra_payload)
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 137, in _fetch_xml
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     raise ApiError(error.attrib['Number'], error.text)
letsencrypt-dns | 2019-10-17 15:13:10 [19] | namecheap.ApiError: 2030166 - Domain is invalid
letsencrypt-dns | 2019-10-17 15:13:10 [19] | During handling of the above exception, another exception occurred:
letsencrypt-dns | 2019-10-17 15:13:10 [19] | Traceback (most recent call last):
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/local/bin/lexicon", line 10, in <module>
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     sys.exit(main())
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     results = client.execute()
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/
letsencrypt-dns | 2019-10-17 15:13:10 [19] | local/lib/python3.7/site-packages/lexicon/client.py", line 71, in execute
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     self.provider.authenticate()
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 69, in authenticate
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     return self._authenticate()
letsencrypt-dns | 2019-10-17 15:13:10 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/namecheap.py", line 127, in _authenticate
letsencrypt-dns | 2019-10-17 15:13:10 [19] |     raise Exception('Authentication failed: `%s`' % str(err))
letsencrypt-dns | 2019-10-17 15:13:10 [19] | Exception: Authentication failed: `2030166 - Domain is invalid`
letsencrypt-dns | 2019-10-17 15:13:10 [19] | Some challenges have failed.

```

**Comment by githtz** [comment]
I've got a similar problem with my namecheap domain at the moment, too. Tried downgrading to an older version but that didn't work. Maybe there were some recent changes to the namecheap api that didn't make it into lexicon yet? Anyhow, any help is much appreciated!
```
2019-12-03 15:10:58 [17] | >>> Creating a certificate for domain(s): -d *.example.org -d example.org
2019-12-03 15:10:59 [17] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-12-03 15:10:59 [17] | Plugins selected: Authenticator manual, Installer None
2019-12-03 15:10:59 [17] | Cert is due for renewal, auto-renewing...
2019-12-03 15:10:59 [17] | Renewing an existing certificate
2019-12-03 15:11:00 [17] | Performing the following challenges:
2019-12-03 15:11:00 [17] | dns-01 challenge for example.org
2019-12-03 15:11:00 [17] | dns-01 challenge for example.org
2019-12-03 15:11:00 [17] | Running manual-auth-hook command: /var/lib/letsencrypt/hooks/authenticator.sh
2019-12-03 15:11:04 [17] | Output from manual-auth-hook command authenticator.sh:
2019-12-03 15:11:04 [17] | Remote: 21
2019-12-03 15:11:04 [17] | To set: 22
2019-12-03 15:11:04 [17] | manual-auth-hook command "/var/lib/letsencrypt/hooks/authenticator.sh" returned error code 1
2019-12-03 15:11:04 [17] | Error output from manual-auth-hook command authenticator.sh:
2019-12-03 15:11:04 [17] | Traceback (most recent call last):
2019-12-03 15:11:04 [17] |   File "/usr/local/bin/lexicon", line 8, in <module>
2019-12-03 15:11:04 [17] |     sys.exit(main())
2019-12-03 15:11:04 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
2019-12-03 15:11:04 [17] |     results = client.execute()
2019-12-03 15:11:04 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 78, in execute
2019-12-03 15:11:04 [17] |     return self.provider.create_record(record_type, name, content)
2019-12-03 15:11:04 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 80, in create_record
2019-12-03 15:11:04 [17] |     return self._create_record(rtype, name, content)
2019-12-03 15:11:04 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/namecheap.py", line 201, in _create_record
2019-12-03 15:11:04 [17] |     self.client.domains_dns_addHost(self.domain, record)
2019-12-03 15:11:04 [17] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 388, in domains_dns_addHost
2019-12-03 15:11:04 [17] |     self._call("namecheap.domains.dns.setHosts", extra_payload)
2019-12-03 15:11:04 [17] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 144, in _call
2019-12-03 15:11:04 [17] |     xml = self._fetch_xml(pa
2019-12-03 15:11:04 [17] | yload, extra_payload)
2019-12-03 15:11:04 [17] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 137, in _fetch_xml
2019-12-03 15:11:04 [17] |     raise ApiError(error.attrib['Number'], error.text)
2019-12-03 15:11:04 [17] | namecheap.ApiError: 2050900 - Please enter a fully qualified domain name.
2019-12-03 15:11:04 [17] | Running manual-auth-hook command: /var/lib/letsencrypt/hooks/authenticator.sh
2019-12-03 15:11:07 [17] | Output from manual-auth-hook command authenticator.sh:
2019-12-03 15:11:07 [17] | Remote: 21
2019-12-03 15:11:07 [17] | To set: 22
2019-12-03 15:11:07 [17] | manual-auth-hook command "/var/lib/letsencrypt/hooks/authenticator.sh" returned error code 1
2019-12-03 15:11:07 [17] | Error output from manual-auth-hook command authenticator.sh:
2019-12-03 15:11:07 [17] | Traceback (most recent call last):
2019-12-03 15:11:07 [17] |   File "/usr/local/bin/lexicon", line 8, in <module>
2019-12-03 15:11:07 [17] |     sys.exit(main())
2019-12-03 15:11:07 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
2019-12-03 15:11:07 [17] |     results = client.execute()
2019-12-03 15:11:07 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 78, in execute
2019-12-03 15:11:07 [17] |     return self.provider.create_record(record_type, name, content)
2019-12-03 15:11:07 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 80, in create_record
2019-12-03 15:11:07 [17] |     return self._create_record(rtype, name, content)
2019-12-03 15:11:07 [17] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/namecheap.py", line 201, in _create_record
2019-12-03 15:11:07 [17] |     self.client.domains_dns_addHost(self.domain, record)
2019-12-03 15:11:07 [17] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 388, in domains_dns_addHost
2019-12-03 15:11:07 [17] |     self._call("namecheap.domains.dns.setHosts", extra_payload)
2019-12-03 15:11:07 [17] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 144, in _call
2019-12-03 15:11:07 [17] |     xml = self._fetch_xml(pa
2019-12-03 15:11:07 [17] | yload, extra_payload)
2019-12-03 15:11:07 [17] |   File "/usr/local/lib/python3.7/site-packages/namecheap.py", line 137, in _fetch_xml
2019-12-03 15:11:07 [17] |     raise ApiError(error.attrib['Number'], error.text)
2019-12-03 15:11:07 [17] | namecheap.ApiError: 2050900 - Please enter a fully qualified domain name.
2019-12-03 15:11:07 [17] | Waiting for verification...
2019-12-03 15:11:09 [17] | Challenge failed for domain example.org
2019-12-03 15:11:09 [17] | Challenge failed for domain example.org
2019-12-03 15:11:09 [17] | dns-01 challenge for example.org
2019-12-03 15:11:09 [17] | dns-01 challenge for example.org
2019-12-03 15:11:09 [17] | Cleaning up challenges
2019-12-03 15:11:09 [17] | Running manual-cleanup-hook command: /var/lib/letsencrypt/hooks/cleanup.sh
2019-12-03 15:11:11 [17] | Running manual-cleanup-hook command: /var/lib/letsencrypt/hooks/cleanup.sh
2019-12-03 15:11:14 [17] | Some challenges have failed.
```

**Comment by adferrand** [comment]
Hello!

Lexicon, that is used to communicate with the DNS provider, makes an elaborate guess for a given domain to understand what is the actual zone handled by your dns provider. If it is obviously `example` in `example.com`, it is less obvious for `example.co.uk` that is still `example`, and not `example.co`. This is done by tldextract, and utility that uses the known TLD in the DNS system.

This allows Lexicon to handle "exotic" tlds, and domains passed to the cli: like on `sub.example.co.uk` is correctly interpretated as the zone `example.co.uk`, where `co.uk` is the TLD.

However, it happens that a DNS provider owns a domain with its own DNS server (here, `com.de`) then delegates the subdomains to customers (in your case, `microtik.com.de`).  In this case, tldextract will wrongly interpretate that the zone to edit is `com.de`.

To prevents that, a flag is designed on Lexicon to explicitly say what is the zone, it is `--delegated`.You can pass it in my Docker using the env variable `LEXICON_OPTIONS` (it would be typically `--delegated microtik.com.de`).

Sadly this option will be applied to all of the domains you handle, so also on `microtik.de`. I will fix that in the next major version of the Docker, but until that, you will need to setup a specific instance of my Docker, with this env variable, for `microtik.com.de`.
