### ISSUE TITLE
ValueError: Requesting acme-v02.api.letsencrypt.org/directory: Connection refused

### ISSUE THREAD

**Issue by MSandro** [adferrand/dnsrobocert#66]
THe Container doesn't generate certificates.

```
ERROR:tldextract:Exception reading Public Suffix List url https://publicsuffix.org/list/public_suffix_list.dat
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
raise err
File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f3fecffd0>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='publicsuffix.org', port=443): Max retries exceeded with url: /list/public_suffix_list.dat (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f3fecffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/tldextract/remote.py", line 37, in find_first_response
resp = session.get(url, timeout=cache_fetch_timeout)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='publicsuffix.org', port=443): Max retries exceeded with url: /list/public_suffix_list.dat (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f3fecffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:tldextract:Exception reading Public Suffix List url https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
raise err
File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f3fe6f5d0>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /publicsuffix/list/master/public_suffix_list.dat (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f3fe6f5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/tldextract/remote.py", line 37, in find_first_response
resp = session.get(url, timeout=cache_fetch_timeout)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /publicsuffix/list/master/public_suffix_list.dat (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f3fe6f5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:tldextract:No Public Suffix List found. Consider using a mirror or constructing your TLDExtract with `suffix_list_urls=None`.
2019-11-08 10:00:20 circus[1] [INFO] Starting master on pid 1
crond[15]: crond (busybox 1.30.1) started, log level 8
2019-11-08 10:00:20 circus[1] [INFO] Arbiter now waiting for commands
2019-11-08 10:00:20 circus[1] [INFO] crond started
2019-11-08 10:00:20 circus[1] [INFO] watch-domains started
2019-11-08 10:00:20 [16] | #### Registering Let's Encrypt account if needed ####
2019-11-08 10:00:20 [16] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-11-08 10:00:20 [16] | An unexpected error occurred:
2019-11-08 10:00:20 [16] | Traceback (most recent call last):
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
2019-11-08 10:00:20 [16] | (self._dns_host, self.port), self.timeout, **extra_kw
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
2019-11-08 10:00:20 [16] | raise err
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
2019-11-08 10:00:20 [16] | sock.connect(sa)
2019-11-08 10:00:20 [16] | ConnectionRefusedError: [Errno 111] Connection refused
2019-11-08 10:00:20 [16] | During handling of the above exception, another exception occurred:
2019-11-08 10:00:20 [16] | Traceback (most recent call last):
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
2019-11-08 10:00:20 [16] | chunked=chunked,
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
2019-11-08 10:00:20 [16] | self._validate_conn(conn)
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
2019-11-08 10:00:20 [16] | conn.connect()
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/conn
2019-11-08 10:00:20 [16] | ection.py", line 334, in connect
2019-11-08 10:00:20 [16] | conn = self._new_conn()
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
2019-11-08 10:00:20 [16] | self, "Failed to establish a new connection: %s" % e
2019-11-08 10:00:20 [16] | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d18f2df10>: Failed to establish a new connection: [Errno 111] Connection refused
2019-11-08 10:00:20 [16] | During handling of the above exception, another exception occurred:
2019-11-08 10:00:20 [16] | Traceback (most recent call last):
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
2019-11-08 10:00:20 [16] | timeout=timeout
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
2019-11-08 10:00:20 [16] | method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
2019-11-08 10:00:20 [16] | raise MaxRetryError(_pool, url, error or ResponseError(cause))
2019-11-08 10:00:20 [16] | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port
2019-11-08 10:00:20 [16] | =443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d18f2df10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2019-11-08 10:00:20 [16] | During handling of the above exception, another exception occurred:
2019-11-08 10:00:20 [16] | Traceback (most recent call last):
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/acme/client.py", line 1110, in _send_request
2019-11-08 10:00:20 [16] | response = self.session.request(method, url, *args, **kwargs)
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
2019-11-08 10:00:20 [16] | resp = self.send(prep, **send_kwargs)
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
2019-11-08 10:00:20 [16] | r = adapter.send(request, **kwargs)
2019-11-08 10:00:20 [16] | File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
2019-11-08 10:00:20 [16] | raise ConnectionError(e, request=request)
2019-11-08 10:00:20 [16] | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /direct
2019-11-08 10:00:20 [16] | ory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d18f2df10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2019-11-08 10:00:20 [16] | During handling of the above exception, another exception occurred:
2019-11-08 10:00:20 [16] | ValueError: Requesting acme-v02.api.letsencrypt.org/directory: Connection refused
2019-11-08 10:00:20 [16] | Please see the logfiles in /etc/letsencrypt/logs for more details.
2019-11-08 10:00:21 [16] | #### Clean autorestart/autocmd jobs
2019-11-08 10:00:21 [16] | #### Creating missing certificates if needed (~1min for each) ####
2019-11-08 10:00:21 [16] | >>> Creating a certificate for domain(s): -d *.h42.co -d h42.co
2019-11-08 10:00:21 [16] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-11-08 10:00:21 [16] | Plugins selected: Authenticator manual, Installer None
2019-11-08 10:00:21 [16] | You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.
2019-11-08 10:00:21 [16] | md5sum: can't open '/etc/letsencrypt/live/h42.co/cert.pem': No such file or directory
2019-11-08 10:00:21 [16] | ### Revoke and delete certificates if needed ####
2019-11-08 10:00:21 [16] | ### Reloading circusd configuration ###
2019-11-08 10:00:22 [16] | ok
```

Logfile:
```
2019-11-08 09:54:44,085:DEBUG:certbot.main:certbot version: 0.39.0
2019-11-08 09:54:44,086:DEBUG:certbot.main:Arguments: ['-n', '--config-dir', '/etc/letsencrypt', '--logs-dir', '/etc/letsencrypt/logs', '--work-dir', '/etc/letsencrypt/work', '--agree-tos', '-m', 'maiersand@gmail.com', '--server', 'https://acme-v02.api.letsencrypt.org/directory']
2019-11-08 09:54:44,086:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-11-08 09:54:44,101:DEBUG:certbot.log:Root logging level set at 20
2019-11-08 09:54:44,102:INFO:certbot.log:Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-11-08 09:54:44,154:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2019-11-08 09:54:44,156:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2019-11-08 09:54:44,163:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c612eb510>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c612eb510>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/acme/client.py", line 1110, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c612eb510>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/certbot/main.py", line 1378, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.7/site-packages/certbot/main.py", line 692, in register
    _determine_account(config)
  File "/usr/local/lib/python3.7/site-packages/certbot/main.py", line 523, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/local/lib/python3.7/site-packages/certbot/client.py", line 176, in register
    acme = acme_from_config_key(config, key)
  File "/usr/local/lib/python3.7/site-packages/certbot/client.py", line 46, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/local/lib/python3.7/site-packages/acme/client.py", line 828, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/local/lib/python3.7/site-packages/acme/client.py", line 1161, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/local/lib/python3.7/site-packages/acme/client.py", line 1133, in _send_request
    raise ValueError("Requesting {0}{1}:{2}".format(host, path, err_msg))
ValueError: Requesting acme-v02.api.letsencrypt.org/directory: Connection refused
2019-11-08 09:54:44,167:ERROR:certbot.log:An unexpected error occurred:
```

```
[root@r1 logs]# curl acme-v02.api.letsencrypt.org/directory
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by adferrand** [comment]
Hello @MSandro, I have published a new version of the Docker. Does it still fail with it?
