### ISSUE TITLE
Error on cleanup stage

### ISSUE THREAD

**Issue by Akkarine** [adferrand/dnsrobocert#75]
DNS-record `_acme-challenge` record has not deleted. Provider: Yandex. Certificates successfully recieved.

Docker log:
```
2020-02-26 14:14:15 [19] | Running manual-auth-hook command: /var/lib/letsencrypt/hooks/authenticator.sh
2020-02-26 14:44:18 [19] | Output from manual-auth-hook command authenticator.sh:
2020-02-26 14:44:18 [19] | RESULT
2020-02-26 14:44:18 [19] | ------
2020-02-26 14:44:18 [19] | True
2020-02-26 14:44:18 [19] | Waiting for verification...
2020-02-26 14:44:25 [19] | Cleaning up challenges
2020-02-26 14:44:25 [19] | Running manual-cleanup-hook command: /var/lib/letsencrypt/hooks/cleanup.sh
2020-02-26 14:44:27 [19] | manual-cleanup-hook command "/var/lib/letsencrypt/hooks/cleanup.sh" returned error code 1
2020-02-26 14:44:27 [19] | Error output from manual-cleanup-hook command cleanup.sh:
2020-02-26 14:44:27 [19] | Traceback (most recent call last):
2020-02-26 14:44:27 [19] |   File "/usr/local/bin/lexicon", line 10, in <module>
2020-02-26 14:44:27 [19] |     sys.exit(main())
2020-02-26 14:44:27 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
2020-02-26 14:44:27 [19] |     results = client.execute()
2020-02-26 14:44:27 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 87, in execute
2020-02-26 14:44:27 [19] |     return self.provider.delete_record(identifier, record_type, name, content)
2020-02-26 14:44:27 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 118, in delete_record
2020-02-26 14:44:27 [19] |     return self._delete_record(identifier=identifier, rtype=rtype, name=name, content=content)
2020-02-26 14:44:27 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 120, in _delete_record
2020-02-26 14:44:27 [19] |     records = self._list_records(rtype, name, content)
2020-02-26 14:44:27 [19] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 76, in _list_records
2020-02-26 14:44:27 [19] |     'content': record['content'],
2020-02-26 14:44:27 [19] | KeyError: 'content'
2020-02-26 14:44:29 [19] | Running deploy-hook command: deploy-hook.sh
```

image: sha256:e5bb88132b06fab2236f473cdc115751323476e0bd7838a5013dd9bb0c8d641f

**Comment by adferrand** [comment]
Hello @Akkarine ! Alongside with the migration of `adferrand/letsencrypt-dns` to `adferrand/dnsrobocert` I also update the version of Lexicon included, which is responsible for the error here.

Could you say if you still see this issue with the latest version of dnsrobocert ?

Kindly regards.

**Comment by Akkarine** [comment]
I'll try for next certificate upgrade (approx 1 month)

**Comment by adferrand** [comment]
@Akkarine, do you still encounter this issue?

**Comment by adferrand** [comment]
I assume that the issue is not existing anymore with fixes done on lexicon. If it is not the case, do not hesitate to say so!
