### ISSUE TITLE
Docker dependency missing

### ISSUE THREAD

**Issue by tcoenraad** [adferrand/dnsrobocert#82]
`docker` is for all related commands (`autocmd`, `autorestart`) missing in `dnsrobocert:3.0.0`. This results in errors like:

``` 
| Renewing an existing certificate
 | Running deploy-hook command: /root/.local/pipx/venvs/dnsrobocert/bin/python -m dnsrobocert.core.hooks -t deploy -c "/tmp/tmpxnp7ye0o/dnsrobocert-runtime.yml" -l "***.nl"
 | Output from deploy-hook command python:
 | business check
 |
 | deploy-hook command "/root/.local/pipx/venvs/dnsrobocert/bin/python -m dnsrobocert.core.hooks -t deploy -c "/tmp/tmpxnp7ye0o/dnsrobocert-runtime.yml" -l "***.nl"" returned error code 1
 | Error output from deploy-hook command python:
 | 2020-03-19 20:10:41 408a9ac70144 __main__[12] ERROR Error while executing the `deploy` hook:
 | 2020-03-19 20:10:41 408a9ac70144 __main__[12] ERROR [Errno 2] No such file or directory: 'docker'
 | Traceback (most recent call last):
 |   File "/root/.local/pipx/venvs/dnsrobocert/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 48, in main
 |     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
 |   File "/root/.local/pipx/venvs/dnsrobocert/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 132, in deploy
 |     _autorestart(certificate)
 |   File "/root/.local/pipx/venvs/dnsrobocert/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 208, in _autorestart
 |     utils.execute(["docker", "restart", container])
 |   File "/root/.local/pipx/venvs/dnsrobocert/lib/python3.8/site-packages/dnsrobocert/core/utils.py", line 28, in execute
 |     process = subprocess.Popen(
 |   File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
 |     self._execute_child(args, executable, preexec_fn, close_fds,
 |   File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
 |     raise child_exception_type(errno_num, err_msg, err_filename)
 | FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

`docker` should be installed from `Dockerfile` to resolve this.

**Comment by adferrand** [comment]
Hello!

Really sorry. I just pushed version `3.0.1` that fixes that by installing the Docker CLI in the Docker image.

**Comment by tcoenraad** [comment]
Thanks!
