### ISSUE TITLE
DNS TXT record check fails on first try when the record is not yet propagated

### ISSUE THREAD

**Issue by Steffaan** [adferrand/dnsrobocert#91]
When starting a certificate renewal the TXT record is added to our DNS. But it takes some time to let it propagate properly.

So i configured a number of checks (max_checks). But it looks like on the first check the DNS query function raises an exception and stops further checking, making the check function useless for me.
In my opinion the check function can be very usefull in my case, when the exception is properly caught and handled and thus making sure the DNS record has been propgated by the provider.

this is what i see in the log:

manual-auth-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp4sobp881/dnsrobocert-runtime.yml" -l "ment.henk.nl"" returned error code 1
Error output from manual-auth-hook command python3:
2020-03-30 10:37:12 a656a11d16c8 __main__[171] INFO Wait 180 seconds before checking that TXT _acme-challenge.ment.henk.nl has the expected value (try 1/4)
2020-03-30 10:40:12 a656a11d16c8 __main__[171] ERROR Error while executing the `auth` hook:
2020-03-30 10:40:12 a656a11d16c8 __main__[171] ERROR The DNS query name does not exist: _acme-challenge.ment.henk.nl.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 48, in main
    globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
  File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 85, in auth
    answers = resolver.query("_acme-challenge.{0}.".format(domain), "TXT")
  File "/usr/lib/python3.8/site-packages/dns/resolver.py", line 1131, in query
    return get_default_resolver().query(qname, rdtype, rdclass, tcp, source,
  File "/usr/lib/python3.8/site-packages/dns/resolver.py", line 1051, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
dns.resolver.NXDOMAIN: The DNS query name does not exist: _acme-challenge.ment.henk.nl.

Waiting for verification...

**Comment by adferrand** [comment]
Indeed, the auth hook is not handling properly the situation where no TXT entries of that kind already exist in the zone. Which is the most common situation...

I opened #93 to fix that and will make a new release once tests are passing.
